# Generated by Django 4.0 on 2022-12-28 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='MainCategoryModel',
            new_name='StateModel',
        ),
        migrations.DeleteModel(
            name='SubCategoryModel',
        ),
        migrations.AddField(
            model_name='citymodel',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.statemodel'),
        ),
    ]
