# Generated by Django 4.0 on 2022-12-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_citymodel_rename_maincategorymodel_statemodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CityModel',
            new_name='EmplyeeModel',
        ),
    ]
