# Generated by Django 4.0 on 2022-12-28 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_citymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.citymodel'),
            preserve_default=False,
        ),
    ]
